[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/api/webhook"
  status = 200
